### ISSUE TITLE
Does not work IPython notebook

### ISSUE THREAD

**Issue by simplygood** [docwhat/itsalltext#53]
itsalltest generally works fine for me.  But I was not able to use it for IPython notebook. It's kind of unstable. It works some times, but mostly it does not work.  Does anyone has this problem? Textarea should meet certain things to be supported by itsalltext?

**Comment by docwhat** [comment]
I've heard of IPython notebook, but never used it. Does it have URLs for viewing in Firefox?

I thought it was an application, not a web page.

**Comment by eigengrau** [comment]
This would be incredibly useful. 

> I thought it was an application, not a web page.

IPython notebooks are web-pages run inside a local or remote web server and displayed inside a browser. Here’s a [demo](http://www.nature.com/news/ipython-interactive-demo-7.21492) of a live notebook (not a statically rendered one; those don’t have text input). If you scroll down inside the iframe shown on the page, you’ll see individual cells containing segments of Python code. Sadly, itsalltext doesn’t seem to be able to work with these. The contents just appear empty when the temporary file is opened. Though I doubt the cells can be easily supported. There is probably a fair deal of JS processing going on in there, since they implement tab completion, etc.

Anyhow, thanks for making itsalltext!

**Comment by xOneca** [comment]
It is a rich text editor which uses a little `textarea` only for event capturing. Does not seem to save full source in any `textarea`, so can't be used with IAT...

**Comment by docwhat** [comment]
Bummer. Closing.
