### ISSUE TITLE
IAT works only when UTF-8 is specified

### ISSUE THREAD

**Issue by ineuw** [docwhat/itsalltext#74]
What other encodings can be specified besides UTF-8, and what is the format to specify them?

**Comment by docwhat** [comment]
The definitive list is [an IANA standard](http://www.iana.org/assignments/character-sets/character-sets.xhtml).  The most common alternative I know of is `UTF-16` or `windows-1252` for some older windows users.

Ciao!

**Comment by ineuw** [comment]
Hi, and thanks for the link IANA link. Did try ISO_8859-1 without a problem.

My second question is (which I forgot to ask the first time). Above the 
encoding, what is 'Seconds between refreshing:' for?  Your reply will be 
most appreciated.

I am trying to resolve a major issue (for me), in which I use your 
add-on to paste text from a Wikisource (Wikipedia)  page into Textpad 
for editing. But, I also use AutoHotkey script to perform some text 
formatting before it's being pasted, and after pasting the document 
encoding is changed to UNIX whereby some keyboard characters are 
altered. I am pursuing this issue for a week and trying to analyze which 
software causes the problem (Firefox 41b1, AutoHotkey, It's All Text and 
Textpad, and my bet is AutoHotkey), for me it's a fascinating process of 
elimination of finding the source. If you are interested in following my 
posts and the replies in the forums, I can send you the links, the posts 
themselves are quite detailed.  I omitted mentioning the use of 
[itsalltext] in the posts because it has always served me well, and it 
would muddy the issue.

Thanks again,

Imre Neuwirth,
ineuw@aei.ca

**Comment by docwhat** [comment]
**Warning: I'm not a Windows user**

IAT monitors files on disk and the web page (looking for newly added `TEXTAREA`s added by Javascript). "Seconds between refreshing" is how often it checks.

The encoding is only for writing the file to disk or sending over the network.  The web page determines the encoding of the text in the browser.  Clipboards don't have an encoding... it is just a series of characters.  It gets an encoding when put someplace like a file.

If you're copying from a `TEXTAREA` then IAT is not the cause.  It doesn't alter the encoding on the web page in anyway.  I recommend leaving it with UTF-8 unless you really know what you're doing.

The way the [Windows clipboard](https://msdn.microsoft.com/en-us/library/ms649013.aspx) works is a bit complicated.  Usually plain text is stored in encoding agnostic Unicode (e.g. there is no encoding in it, because it is just a bunch of characters).  However, it is also possible for the clipboard to hold more than one version. For example, it might have plain text as well as RTF or HTML.  If you think this is the problem, then paste the text into `notepad.exe` and then copy it out again.  That should "reset" it back to just plain text.

Another option is get something to monitor what the clipboard is really doing.  Quick searching shows [ClipSpy+](http://www.codeproject.com/Articles/22624/ClipSpy) might do what you want... but I'm not a Windows expert. :disappointed: 

I hope that helps.

PS: Feel free to link your forum posts, it might help someone else.

**Comment by ineuw** [comment]
Thanks so much. Your information is invaluable by clarifying a number of 
issues of which I was ignorant. And I will link the posts in Github.
