### ISSUE TITLE
Compatibility with Thunderbird 45.5.1

### ISSUE THREAD

**Issue by amaramrahul** [docwhat/itsalltext#85]
Is there any possibility that this plugin can be used with Thunderbird 45.5.1 in OS X? I'm looking at a specific use case actually. I use the Webapp tabs plugin to load URLs directly as tabs in thunderbird. Considering that this is the same as in Firefox browser, would it be too difficult to have Itsalltext work in Thunderbird? I am willing to make a small donation of 10 USD as an encouragement for making this plugin compatible with Thunderbird 45.5.1 in OS X :).

**Comment by docwhat** [comment]
I don't use Thunderbird.  Since I don't use or test it, I'm hesitant to just enable it.  I doubt IAT has any use unless you have that specific plugin.

At work I use IBM Notes, which can do the same thing (open web-pages in tabs) and I hate it.  It lacks a lot of the features of my normal browser and if Notes crashes or I reboot, it takes everything with it.

You can take it for a try, though, by fetching the `.xpi` directly from addons.mozilla.org installing (I think): https://support.mozilla.org/en-US/kb/thunderbird-add-ons-frequently-asked-questions#w_installing-add-ons-downloaded-from-outside-thunderbird-e-g-using-a-web-browser-like-firefox
